spring:
    datasource:
        url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres?user=postgres.nmcgdztcymerhtkgdots&password=XdF37GAA4P8seyyM
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
aws:
    s3:
        bucket-name: ${SUPABASE_BUCKET_NAME:helpline-storage}
api:
    security:
        token:
            secret: ${JWT_SECRET:my-secret}
springdoc:
    swagger-ui:
        path: "/docs"
